export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <div style={{ maxWidth: '70%', margin: '50px auto' }}>{children}</div>;
}
